// Code generated by MockGen. DO NOT EDIT.
// Source: dcp/listresultreader.go

// Package dcp is a generated GoMock package.
package dcp

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockListingResultReader is a mock of ListingResultReader interface
type MockListingResultReader struct {
	ctrl     *gomock.Controller
	recorder *MockListingResultReaderMockRecorder
}

// MockListingResultReaderMockRecorder is the mock recorder for MockListingResultReader
type MockListingResultReaderMockRecorder struct {
	mock *MockListingResultReader
}

// NewMockListingResultReader creates a new mock instance
func NewMockListingResultReader(ctrl *gomock.Controller) *MockListingResultReader {
	mock := &MockListingResultReader{ctrl: ctrl}
	mock.recorder = &MockListingResultReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockListingResultReader) EXPECT() *MockListingResultReaderMockRecorder {
	return m.recorder
}

// ReadListResult mocks base method
func (m *MockListingResultReader) ReadListResult(ctx context.Context, bucketName, objectName string) (chan string, error) {
	ret := m.ctrl.Call(m, "ReadListResult", ctx, bucketName, objectName)
	ret0, _ := ret[0].(chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadListResult indicates an expected call of ReadListResult
func (mr *MockListingResultReaderMockRecorder) ReadListResult(ctx, bucketName, objectName interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadListResult", reflect.TypeOf((*MockListingResultReader)(nil).ReadListResult), ctx, bucketName, objectName)
}
