# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate app engine config file to deploy in either test or prod environment.
"""

import argparse
import os

_CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))

_TEMPLATE_CONFIG_PATH = os.path.join(_CURRENT_DIR, 'app.yaml.template')

_OUTPUT_CONFIG_PATH = os.path.join(_CURRENT_DIR, 'app.{}.yaml')

_AUTO_GENERATED_COMMENT = '''\
# DO NOT EDIT. Code generated by app_engine_config_generator.py.
# Run python app_engine_config_generator.py --help for more information on how
# to generate this file.
'''

def generate_config(environment):
    """Generates app engine config file based on the environment string."""
    with open(_TEMPLATE_CONFIG_PATH, 'r') as template_file:
        template_content = template_file.read()

    generated_content = template_content.format(environment)

    generate_file_path = _OUTPUT_CONFIG_PATH.format(environment)
    with open(generate_file_path, 'w') as generated_file:
        generated_file.write(
            '{}\n{}'.format(_AUTO_GENERATED_COMMENT, generated_content))

def main():
    """Main function parses the input args and generates the config."""
    parser = argparse.ArgumentParser(
        description='Generate app.yaml app engine config file')

    parser.add_argument('environment',
                        choices=['test', 'prod', 'perf'],
                        help='Whether to generate the app engine config for '
                             'test or prod environment.')
    args = parser.parse_args()
    generate_config(args.environment)


if __name__ == '__main__':
    main()
