# TODO(mbassiouny): Move the base image to Google official repository.
FROM gcr.io/mbassiouny-test/cloud-ingest:base

# Set the working directory to /cloud-ingest
WORKDIR /cloud-ingest

ADD create-infra /cloud-ingest/create-infra
ADD cloud-functions /cloud-ingest/cloud-functions
ADD dcpmain /cloud-ingest/

# Default running bash when the container launches
CMD ["/bin/bash"]
