FROM google/cloud-sdk:latest

RUN apt-get install -y python-pip python-dev
RUN apt-get install -y golang-go

# Set the working directory to /cloud-ingest
WORKDIR /cloud-ingest

# Copy the current directory contents into the container at /cloud-ingest
ADD ./requirements.txt /cloud-ingest

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Default running bash when the container launches
CMD ["/bin/bash"]
