// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pulse.proto

package pulse_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The Agent periodically sends this msg to the DCP. The DCP uses this info to
// know that the Agent is alive, and to expose info about that Agent.
type Msg struct {
	AgentId               *AgentId `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Frequency             int32    `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	AgentVersion          string   `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentLogsDir          string   `protobuf:"bytes,4,opt,name=agent_logs_dir,json=agentLogsDir,proto3" json:"agent_logs_dir,omitempty"`
	AgentTransferredBytes int64    `protobuf:"varint,6,opt,name=agent_transferred_bytes,json=agentTransferredBytes,proto3" json:"agent_transferred_bytes,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_pulse_47bc9d5757892c27, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetAgentId() *AgentId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Msg) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *Msg) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *Msg) GetAgentLogsDir() string {
	if m != nil {
		return m.AgentLogsDir
	}
	return ""
}

func (m *Msg) GetAgentTransferredBytes() int64 {
	if m != nil {
		return m.AgentTransferredBytes
	}
	return 0
}

// This message stores a unique identifier for each agent.
// The DCP can use this to separate each agent and monitor future behaviors.
type AgentId struct {
	HostName             string   `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	ProcessId            string   `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentId) Reset()         { *m = AgentId{} }
func (m *AgentId) String() string { return proto.CompactTextString(m) }
func (*AgentId) ProtoMessage()    {}
func (*AgentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_pulse_47bc9d5757892c27, []int{1}
}
func (m *AgentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentId.Unmarshal(m, b)
}
func (m *AgentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentId.Marshal(b, m, deterministic)
}
func (dst *AgentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentId.Merge(dst, src)
}
func (m *AgentId) XXX_Size() int {
	return xxx_messageInfo_AgentId.Size(m)
}
func (m *AgentId) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentId.DiscardUnknown(m)
}

var xxx_messageInfo_AgentId proto.InternalMessageInfo

func (m *AgentId) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *AgentId) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "cloud_ingest_pulse.Msg")
	proto.RegisterType((*AgentId)(nil), "cloud_ingest_pulse.AgentId")
}

func init() { proto.RegisterFile("pulse.proto", fileDescriptor_pulse_47bc9d5757892c27) }

var fileDescriptor_pulse_47bc9d5757892c27 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0x87, 0xc9, 0x7e, 0x74, 0xed, 0xbb, 0xef, 0x77, 0x8c, 0x80, 0x58, 0x98, 0x42, 0x99, 0x1e,
	0x7a, 0xea, 0x41, 0x61, 0x77, 0x87, 0x1e, 0x26, 0xea, 0xa1, 0x88, 0x07, 0x2f, 0xa1, 0x6b, 0xde,
	0xc5, 0x42, 0x97, 0xd4, 0xbc, 0xa9, 0xb0, 0xff, 0xd7, 0x3f, 0x44, 0x9a, 0x0e, 0x26, 0x78, 0x6a,
	0x79, 0x9e, 0x87, 0x90, 0x7c, 0x60, 0xda, 0xb4, 0x35, 0x61, 0xd6, 0x58, 0xe3, 0x0c, 0xe7, 0x65,
	0x6d, 0x5a, 0x29, 0x2a, 0xad, 0x90, 0x9c, 0xf0, 0x66, 0xf9, 0xcd, 0x60, 0xf8, 0x4c, 0x8a, 0xaf,
	0x20, 0x2c, 0x14, 0x6a, 0x27, 0x2a, 0x19, 0xb3, 0x84, 0xa5, 0xd3, 0x9b, 0x45, 0xf6, 0x37, 0xcf,
	0xee, 0xba, 0x66, 0x23, 0xf3, 0x49, 0xd1, 0xff, 0xf0, 0x0b, 0x88, 0x76, 0x16, 0x3f, 0x5b, 0xd4,
	0xe5, 0x21, 0x1e, 0x24, 0x2c, 0x1d, 0xe7, 0x27, 0xc0, 0xaf, 0xe0, 0x7f, 0x7f, 0xea, 0x17, 0x5a,
	0xaa, 0x8c, 0x8e, 0x87, 0x09, 0x4b, 0xa3, 0xfc, 0x9f, 0x87, 0x6f, 0x3d, 0xe3, 0xd7, 0x30, 0xeb,
	0xa3, 0xda, 0x28, 0x12, 0xb2, 0xb2, 0xf1, 0xe8, 0x57, 0xf5, 0x64, 0x14, 0xdd, 0x57, 0x96, 0xaf,
	0xe0, 0xbc, 0xaf, 0x9c, 0x2d, 0x34, 0xed, 0xd0, 0x5a, 0x94, 0x62, 0x7b, 0x70, 0x48, 0x71, 0x90,
	0xb0, 0x74, 0x98, 0x9f, 0x79, 0xfd, 0x7a, 0xb2, 0xeb, 0x4e, 0x3e, 0x8e, 0xc2, 0xf1, 0x3c, 0x58,
	0x3e, 0xc0, 0xe4, 0x78, 0x75, 0xbe, 0x80, 0xe8, 0xc3, 0x90, 0x13, 0xba, 0xd8, 0xa3, 0x7f, 0x6a,
	0x94, 0x87, 0x1d, 0x78, 0x29, 0xf6, 0xc8, 0x2f, 0x01, 0x1a, 0x6b, 0x4a, 0x24, 0xea, 0x86, 0x18,
	0x78, 0x1b, 0x1d, 0xc9, 0x46, 0xae, 0xe7, 0xef, 0x33, 0xbf, 0x83, 0x50, 0x46, 0xf8, 0x4d, 0xb7,
	0x81, 0xff, 0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x63, 0xce, 0x9f, 0x2a, 0x69, 0x01, 0x00,
	0x00,
}
