// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pulse.proto

package pulse_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This message allows the DCP to determine if each agent is alive or dead.
type Msg struct {
	AgentId                    *AgentId `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Frequency                  int32    `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	AgentVersion               string   `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentLogsDir               string   `protobuf:"bytes,4,opt,name=agent_logs_dir,json=agentLogsDir,proto3" json:"agent_logs_dir,omitempty"`
	AgentThroughputBytesPerSec int64    `protobuf:"varint,5,opt,name=agent_throughput_bytes_per_sec,json=agentThroughputBytesPerSec,proto3" json:"agent_throughput_bytes_per_sec,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_pulse_31c196d99a590b76, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetAgentId() *AgentId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Msg) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *Msg) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *Msg) GetAgentLogsDir() string {
	if m != nil {
		return m.AgentLogsDir
	}
	return ""
}

func (m *Msg) GetAgentThroughputBytesPerSec() int64 {
	if m != nil {
		return m.AgentThroughputBytesPerSec
	}
	return 0
}

// This message stores a unique identifier for each agent.
// The DCP can use this to separate each agent and monitor future behaviors.
type AgentId struct {
	HostName             string   `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	ProcessId            string   `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentId) Reset()         { *m = AgentId{} }
func (m *AgentId) String() string { return proto.CompactTextString(m) }
func (*AgentId) ProtoMessage()    {}
func (*AgentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_pulse_31c196d99a590b76, []int{1}
}
func (m *AgentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentId.Unmarshal(m, b)
}
func (m *AgentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentId.Marshal(b, m, deterministic)
}
func (dst *AgentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentId.Merge(dst, src)
}
func (m *AgentId) XXX_Size() int {
	return xxx_messageInfo_AgentId.Size(m)
}
func (m *AgentId) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentId.DiscardUnknown(m)
}

var xxx_messageInfo_AgentId proto.InternalMessageInfo

func (m *AgentId) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *AgentId) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "cloud_ingest_pulse.Msg")
	proto.RegisterType((*AgentId)(nil), "cloud_ingest_pulse.AgentId")
}

func init() { proto.RegisterFile("pulse.proto", fileDescriptor_pulse_31c196d99a590b76) }

var fileDescriptor_pulse_31c196d99a590b76 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xc6, 0xda, 0x66, 0xaa, 0x45, 0xf6, 0x14, 0xac, 0x4a, 0xa8, 0x1e, 0x72, 0xca,
	0x41, 0xc1, 0xbb, 0x41, 0x0f, 0x05, 0x15, 0x89, 0xe2, 0xc1, 0xcb, 0x92, 0x26, 0xe3, 0x26, 0x90,
	0x66, 0xe2, 0xce, 0x46, 0xe8, 0x5f, 0xf6, 0x57, 0x48, 0x36, 0x45, 0x05, 0x4f, 0xbb, 0x7c, 0xef,
	0x63, 0xe0, 0x3d, 0x98, 0xb5, 0x5d, 0xcd, 0x18, 0xb7, 0x86, 0x2c, 0x49, 0x99, 0xd7, 0xd4, 0x15,
	0xaa, 0x6a, 0x34, 0xb2, 0x55, 0x2e, 0x59, 0x7e, 0x09, 0xf0, 0x1e, 0x58, 0xcb, 0x6b, 0x98, 0x66,
	0x1a, 0x1b, 0xab, 0xaa, 0x22, 0x10, 0xa1, 0x88, 0x66, 0x97, 0x8b, 0xf8, 0xbf, 0x1e, 0xdf, 0xf4,
	0xce, 0xaa, 0x48, 0x27, 0xd9, 0xf0, 0x91, 0x27, 0xe0, 0xbf, 0x1b, 0xfc, 0xe8, 0xb0, 0xc9, 0xb7,
	0xc1, 0x28, 0x14, 0xd1, 0x38, 0xfd, 0x05, 0xf2, 0x1c, 0x0e, 0x87, 0xab, 0x9f, 0x68, 0xb8, 0xa2,
	0x26, 0xf0, 0x42, 0x11, 0xf9, 0xe9, 0x81, 0x83, 0xaf, 0x03, 0x93, 0x17, 0x30, 0x1f, 0xa4, 0x9a,
	0x34, 0xab, 0xa2, 0x32, 0xc1, 0xde, 0x1f, 0xeb, 0x9e, 0x34, 0xdf, 0x56, 0x46, 0x26, 0x70, 0x36,
	0x58, 0xb6, 0x34, 0xd4, 0xe9, 0xb2, 0xed, 0xac, 0x5a, 0x6f, 0x2d, 0xb2, 0x6a, 0xd1, 0x28, 0xc6,
	0x3c, 0x18, 0x87, 0x22, 0xf2, 0xd2, 0x63, 0x67, 0xbd, 0xfc, 0x48, 0x49, 0xef, 0x3c, 0xa1, 0x79,
	0xc6, 0x7c, 0x79, 0x07, 0x93, 0x5d, 0x01, 0xb9, 0x00, 0xbf, 0x24, 0xb6, 0xaa, 0xc9, 0x36, 0xe8,
	0x0a, 0xfb, 0xe9, 0xb4, 0x07, 0x8f, 0xd9, 0x06, 0xe5, 0x29, 0x40, 0x6b, 0x28, 0x47, 0xe6, 0x7e,
	0x8e, 0x91, 0x4b, 0xfd, 0x1d, 0x59, 0x15, 0xc9, 0xd1, 0xdb, 0xdc, 0xad, 0xa1, 0x34, 0x29, 0xb7,
	0xec, 0x7a, 0xdf, 0x3d, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x6e, 0xd8, 0xdf, 0x6f,
	0x01, 0x00, 0x00,
}
