// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tasks.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/tasks.proto

It has these top-level messages:
	TaskFailureType
	TaskStatus
	TaskType
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Specifies the classes of failures that a task can have.
type TaskFailureType_Type int32

const (
	// Not used.
	TaskFailureType_UNUSED TaskFailureType_Type = 0
	// The failure type is not known / unrecognized.
	TaskFailureType_UNKNOWN TaskFailureType_Type = 1
	// The file was modified at source while being uploaded.
	TaskFailureType_FILE_MODIFIED_FAILURE TaskFailureType_Type = 2
	// File MD5 hash does not match GCS MD5 hash.
	TaskFailureType_MD5_MISMATCH_FAILURE TaskFailureType_Type = 3
	// GCS upload failed due to a precondition failure.
	TaskFailureType_PRECONDITION_FAILURE TaskFailureType_Type = 4
	// Agent asked to upload a file that does not exist.
	TaskFailureType_FILE_NOT_FOUND_FAILURE TaskFailureType_Type = 5
	// Agent does not have permissions for requested action.
	TaskFailureType_PERMISSION_FAILURE TaskFailureType_Type = 6
)

var TaskFailureType_Type_name = map[int32]string{
	0: "UNUSED",
	1: "UNKNOWN",
	2: "FILE_MODIFIED_FAILURE",
	3: "MD5_MISMATCH_FAILURE",
	4: "PRECONDITION_FAILURE",
	5: "FILE_NOT_FOUND_FAILURE",
	6: "PERMISSION_FAILURE",
}
var TaskFailureType_Type_value = map[string]int32{
	"UNUSED":                 0,
	"UNKNOWN":                1,
	"FILE_MODIFIED_FAILURE":  2,
	"MD5_MISMATCH_FAILURE":   3,
	"PRECONDITION_FAILURE":   4,
	"FILE_NOT_FOUND_FAILURE": 5,
	"PERMISSION_FAILURE":     6,
}

func (x TaskFailureType_Type) String() string {
	return proto1.EnumName(TaskFailureType_Type_name, int32(x))
}
func (TaskFailureType_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Specifies the current status of the cloud ingest task.
type TaskStatus_Type int32

const (
	// The task is unqueued waiting to be queued by the dcp.
	TaskStatus_UNQUEUED TaskStatus_Type = 0
	// The task is in process.
	TaskStatus_QUEUED TaskStatus_Type = 1
	// The task was completed but failed.
	TaskStatus_FAILED TaskStatus_Type = 2
	// The task was completed and succeeded.
	TaskStatus_SUCCESS TaskStatus_Type = 3
)

var TaskStatus_Type_name = map[int32]string{
	0: "UNQUEUED",
	1: "QUEUED",
	2: "FAILED",
	3: "SUCCESS",
}
var TaskStatus_Type_value = map[string]int32{
	"UNQUEUED": 0,
	"QUEUED":   1,
	"FAILED":   2,
	"SUCCESS":  3,
}

func (x TaskStatus_Type) String() string {
	return proto1.EnumName(TaskStatus_Type_name, int32(x))
}
func (TaskStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Specifies the task operation that a task performs.
type TaskType_Type int32

const (
	// Unknown task type.
	TaskType_UNKNOWN TaskType_Type = 0
	// List task. A task that lists the files on the on-premises directory.
	TaskType_LIST TaskType_Type = 1
	// Upload to GCS task. Upload a file from the on-premises directory to GCS.
	TaskType_UPLOAD_GCS TaskType_Type = 2
)

var TaskType_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "LIST",
	2: "UPLOAD_GCS",
}
var TaskType_Type_value = map[string]int32{
	"UNKNOWN":    0,
	"LIST":       1,
	"UPLOAD_GCS": 2,
}

func (x TaskType_Type) String() string {
	return proto1.EnumName(TaskType_Type_name, int32(x))
}
func (TaskType_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// Message to wrap the task failure type. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskFailureType struct {
}

func (m *TaskFailureType) Reset()                    { *m = TaskFailureType{} }
func (m *TaskFailureType) String() string            { return proto1.CompactTextString(m) }
func (*TaskFailureType) ProtoMessage()               {}
func (*TaskFailureType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Message to wrap the task status. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskStatus struct {
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto1.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Message to wrap the task type. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskType struct {
}

func (m *TaskType) Reset()                    { *m = TaskType{} }
func (m *TaskType) String() string            { return proto1.CompactTextString(m) }
func (*TaskType) ProtoMessage()               {}
func (*TaskType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*TaskFailureType)(nil), "TaskFailureType")
	proto1.RegisterType((*TaskStatus)(nil), "TaskStatus")
	proto1.RegisterType((*TaskType)(nil), "TaskType")
	proto1.RegisterEnum("TaskFailureType_Type", TaskFailureType_Type_name, TaskFailureType_Type_value)
	proto1.RegisterEnum("TaskStatus_Type", TaskStatus_Type_name, TaskStatus_Type_value)
	proto1.RegisterEnum("TaskType_Type", TaskType_Type_name, TaskType_Type_value)
}

func init() { proto1.RegisterFile("proto/tasks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xd7, 0xae, 0xeb, 0xca, 0xa7, 0x68, 0x0c, 0x3a, 0xd4, 0x63, 0xef, 0xea, 0x41, 0x3c,
	0xec, 0x58, 0x9b, 0x74, 0x06, 0xdb, 0xa4, 0x36, 0xf9, 0x10, 0xbc, 0x84, 0x0a, 0x3b, 0xc8, 0x84,
	0x8d, 0xb5, 0x3b, 0xf8, 0x77, 0xfc, 0x11, 0xfe, 0x3e, 0x49, 0x28, 0xdb, 0x4e, 0x79, 0xe0, 0xe5,
	0x7b, 0x78, 0xdf, 0xc0, 0xc5, 0x66, 0xbb, 0xee, 0xd7, 0x0f, 0x7d, 0xdb, 0xad, 0xba, 0x7b, 0xcf,
	0xe9, 0x5f, 0x00, 0xe7, 0xa6, 0xed, 0x56, 0x45, 0xfb, 0xf5, 0xbd, 0xdb, 0x2e, 0xcd, 0xcf, 0x66,
	0x99, 0xfe, 0x06, 0x10, 0x39, 0xa0, 0x00, 0x31, 0x4a, 0xd4, 0x9c, 0x91, 0x11, 0x3d, 0x81, 0x29,
	0xca, 0x57, 0xa9, 0xde, 0x25, 0x09, 0xe8, 0x0d, 0x5c, 0x15, 0xa2, 0xe4, 0xb6, 0x52, 0x4c, 0x14,
	0x82, 0x33, 0x5b, 0x64, 0xa2, 0xc4, 0x86, 0x93, 0x90, 0x5e, 0xc3, 0x65, 0xc5, 0x9e, 0x6c, 0x25,
	0x74, 0x95, 0x99, 0xfc, 0x65, 0x9f, 0x8c, 0x5d, 0x52, 0x37, 0x3c, 0x57, 0x92, 0x09, 0x23, 0x94,
	0xdc, 0x27, 0x11, 0xbd, 0x85, 0x99, 0xd7, 0x49, 0x65, 0x6c, 0xa1, 0x50, 0x1e, 0x7c, 0x13, 0x3a,
	0x03, 0x5a, 0xf3, 0xa6, 0x12, 0x5a, 0x1f, 0xdf, 0xc4, 0xe9, 0x02, 0xc0, 0xf5, 0xd6, 0x7d, 0xdb,
	0xef, 0xba, 0x74, 0x3e, 0x34, 0x3e, 0x85, 0x04, 0xe5, 0x1b, 0x72, 0xf4, 0x9d, 0x01, 0xe2, 0x81,
	0x03, 0xc7, 0xee, 0x98, 0x33, 0x12, 0xba, 0x2d, 0x1a, 0xf3, 0x9c, 0x6b, 0x4d, 0xc6, 0xe9, 0x1c,
	0x12, 0x27, 0xf2, 0xcb, 0xef, 0x06, 0xcd, 0xd1, 0xd8, 0x11, 0x4d, 0x20, 0x2a, 0x85, 0x36, 0x24,
	0xa0, 0x67, 0x00, 0x58, 0x97, 0x2a, 0x63, 0x76, 0x91, 0x6b, 0x12, 0x3e, 0x4f, 0x3f, 0x26, 0xfe,
	0x17, 0x3f, 0x63, 0xff, 0x3c, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x20, 0x46, 0x9d, 0xb9, 0x61,
	0x01, 0x00, 0x00,
}
