// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tasks.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/tasks.proto

It has these top-level messages:
	TaskFailureType
	TaskStatus
	TaskType
	JobRunStatus
	ResourceStatus
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Specifies the classes of failures that a task can have.
type TaskFailureType_Type int32

const (
	// Not used.
	TaskFailureType_UNUSED TaskFailureType_Type = 0
	// The failure type is not known / unrecognized.
	TaskFailureType_UNKNOWN TaskFailureType_Type = 1
	// The file was modified at source while being uploaded.
	TaskFailureType_FILE_MODIFIED_FAILURE TaskFailureType_Type = 2
	// File MD5 hash does not match GCS MD5 hash.
	TaskFailureType_MD5_MISMATCH_FAILURE TaskFailureType_Type = 3
	// GCS upload failed due to a precondition failure.
	TaskFailureType_PRECONDITION_FAILURE TaskFailureType_Type = 4
	// Agent asked to upload a file that does not exist.
	TaskFailureType_FILE_NOT_FOUND_FAILURE TaskFailureType_Type = 5
	// Agent does not have permissions for requested action.
	TaskFailureType_PERMISSION_FAILURE TaskFailureType_Type = 6
)

var TaskFailureType_Type_name = map[int32]string{
	0: "UNUSED",
	1: "UNKNOWN",
	2: "FILE_MODIFIED_FAILURE",
	3: "MD5_MISMATCH_FAILURE",
	4: "PRECONDITION_FAILURE",
	5: "FILE_NOT_FOUND_FAILURE",
	6: "PERMISSION_FAILURE",
}
var TaskFailureType_Type_value = map[string]int32{
	"UNUSED":                 0,
	"UNKNOWN":                1,
	"FILE_MODIFIED_FAILURE":  2,
	"MD5_MISMATCH_FAILURE":   3,
	"PRECONDITION_FAILURE":   4,
	"FILE_NOT_FOUND_FAILURE": 5,
	"PERMISSION_FAILURE":     6,
}

func (x TaskFailureType_Type) String() string {
	return proto1.EnumName(TaskFailureType_Type_name, int32(x))
}
func (TaskFailureType_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Specifies the current status of the cloud ingest task.
type TaskStatus_Type int32

const (
	// The task is unqueued waiting to be queued by the dcp.
	TaskStatus_UNQUEUED TaskStatus_Type = 0
	// The task is in process.
	TaskStatus_QUEUED TaskStatus_Type = 1
	// The task was completed but failed.
	TaskStatus_FAILED TaskStatus_Type = 2
	// The task was completed and succeeded.
	TaskStatus_SUCCESS TaskStatus_Type = 3
)

var TaskStatus_Type_name = map[int32]string{
	0: "UNQUEUED",
	1: "QUEUED",
	2: "FAILED",
	3: "SUCCESS",
}
var TaskStatus_Type_value = map[string]int32{
	"UNQUEUED": 0,
	"QUEUED":   1,
	"FAILED":   2,
	"SUCCESS":  3,
}

func (x TaskStatus_Type) String() string {
	return proto1.EnumName(TaskStatus_Type_name, int32(x))
}
func (TaskStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Specifies the task operation that a task performs.
type TaskType_Type int32

const (
	// Unknown task type.
	TaskType_UNKNOWN TaskType_Type = 0
	// List task. A task that lists the files on the on-premises directory.
	TaskType_LIST TaskType_Type = 1
	// Copy task. Upload a file from the on-premises directory to GCS.
	TaskType_COPY TaskType_Type = 2
)

var TaskType_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "LIST",
	2: "COPY",
}
var TaskType_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"LIST":    1,
	"COPY":    2,
}

func (x TaskType_Type) String() string {
	return proto1.EnumName(TaskType_Type_name, int32(x))
}
func (TaskType_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// Specifies the type of the Job Run status.
type JobRunStatus_Type int32

const (
	// Indicates that a job hasn't been started.
	JobRunStatus_NOT_STARTED JobRunStatus_Type = 0
	// Indicates that the job has been started and is in progress.
	JobRunStatus_IN_PROGRESS JobRunStatus_Type = 1
	// Indicates that the job has completed but it failed.
	JobRunStatus_FAILED JobRunStatus_Type = 2
	// Indicates that the job has completed and it succeeded.
	JobRunStatus_SUCCESS JobRunStatus_Type = 3
)

var JobRunStatus_Type_name = map[int32]string{
	0: "NOT_STARTED",
	1: "IN_PROGRESS",
	2: "FAILED",
	3: "SUCCESS",
}
var JobRunStatus_Type_value = map[string]int32{
	"NOT_STARTED": 0,
	"IN_PROGRESS": 1,
	"FAILED":      2,
	"SUCCESS":     3,
}

func (x JobRunStatus_Type) String() string {
	return proto1.EnumName(JobRunStatus_Type_name, int32(x))
}
func (JobRunStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ResourceStatus_Type int32

const (
	// Unspecified.
	ResourceStatus_TYPE_UNSPECIFIED ResourceStatus_Type = 0
	// This resource is active and running as expected.
	ResourceStatus_RUNNING ResourceStatus_Type = 1
	// This resource is in the process of deploying.
	ResourceStatus_DEPLOYING ResourceStatus_Type = 2
	// This resource is in the process of deleting.
	ResourceStatus_DELETING ResourceStatus_Type = 3
	// This resource is tried to deploy and failed.
	ResourceStatus_FAILED ResourceStatus_Type = 4
	// This resource was not found.
	ResourceStatus_NOT_FOUND ResourceStatus_Type = 5
	// Tried to retrieve the status of this resource but it is unknown.
	ResourceStatus_UNKNOWN ResourceStatus_Type = 6
)

var ResourceStatus_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "RUNNING",
	2: "DEPLOYING",
	3: "DELETING",
	4: "FAILED",
	5: "NOT_FOUND",
	6: "UNKNOWN",
}
var ResourceStatus_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"RUNNING":          1,
	"DEPLOYING":        2,
	"DELETING":         3,
	"FAILED":           4,
	"NOT_FOUND":        5,
	"UNKNOWN":          6,
}

func (x ResourceStatus_Type) String() string {
	return proto1.EnumName(ResourceStatus_Type_name, int32(x))
}
func (ResourceStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

// Message to wrap the task failure type. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskFailureType struct {
}

func (m *TaskFailureType) Reset()                    { *m = TaskFailureType{} }
func (m *TaskFailureType) String() string            { return proto1.CompactTextString(m) }
func (*TaskFailureType) ProtoMessage()               {}
func (*TaskFailureType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Message to wrap the task status. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskStatus struct {
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto1.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Message to wrap the task type. This is needed to create a scope that does
// not conflict with other enums in this file.
type TaskType struct {
}

func (m *TaskType) Reset()                    { *m = TaskType{} }
func (m *TaskType) String() string            { return proto1.CompactTextString(m) }
func (*TaskType) ProtoMessage()               {}
func (*TaskType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Message to wrap the Job Status type. This is needed to create a scope that
// does not conflict with other enums in this file.
type JobRunStatus struct {
}

func (m *JobRunStatus) Reset()                    { *m = JobRunStatus{} }
func (m *JobRunStatus) String() string            { return proto1.CompactTextString(m) }
func (*JobRunStatus) ProtoMessage()               {}
func (*JobRunStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Message to wrap the Resource status type. This is needed to create a scope
// that does not conflict with other enums in this file.
type ResourceStatus struct {
}

func (m *ResourceStatus) Reset()                    { *m = ResourceStatus{} }
func (m *ResourceStatus) String() string            { return proto1.CompactTextString(m) }
func (*ResourceStatus) ProtoMessage()               {}
func (*ResourceStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto1.RegisterType((*TaskFailureType)(nil), "TaskFailureType")
	proto1.RegisterType((*TaskStatus)(nil), "TaskStatus")
	proto1.RegisterType((*TaskType)(nil), "TaskType")
	proto1.RegisterType((*JobRunStatus)(nil), "JobRunStatus")
	proto1.RegisterType((*ResourceStatus)(nil), "ResourceStatus")
	proto1.RegisterEnum("TaskFailureType_Type", TaskFailureType_Type_name, TaskFailureType_Type_value)
	proto1.RegisterEnum("TaskStatus_Type", TaskStatus_Type_name, TaskStatus_Type_value)
	proto1.RegisterEnum("TaskType_Type", TaskType_Type_name, TaskType_Type_value)
	proto1.RegisterEnum("JobRunStatus_Type", JobRunStatus_Type_name, JobRunStatus_Type_value)
	proto1.RegisterEnum("ResourceStatus_Type", ResourceStatus_Type_name, ResourceStatus_Type_value)
}

func init() { proto1.RegisterFile("proto/tasks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xbd, 0xce, 0xd3, 0x30,
	0x14, 0x6d, 0xd2, 0x34, 0x2d, 0xb7, 0x85, 0x1a, 0xab, 0x54, 0xc0, 0x98, 0x85, 0x0d, 0x86, 0x8a,
	0x81, 0x31, 0xc4, 0x4e, 0x31, 0x24, 0x76, 0xea, 0x1f, 0xa1, 0xb2, 0x44, 0x29, 0xca, 0x80, 0x8a,
	0x9a, 0xaa, 0x49, 0x06, 0x36, 0x9e, 0x85, 0x87, 0xe0, 0xf9, 0x90, 0x4d, 0xd4, 0x2f, 0xd3, 0x37,
	0xf9, 0x5c, 0x5d, 0xdf, 0x73, 0xcf, 0x39, 0x36, 0x3c, 0xbf, 0xde, 0x9a, 0xae, 0x79, 0xd7, 0x55,
	0xed, 0xb9, 0x7d, 0xeb, 0x70, 0xf4, 0xd7, 0x83, 0xb5, 0xae, 0xda, 0x73, 0x5a, 0xfd, 0xf8, 0xd9,
	0xdf, 0x6a, 0xfd, 0xeb, 0x5a, 0x47, 0x7f, 0x3c, 0x08, 0x2c, 0xc0, 0x00, 0xa1, 0xe1, 0x46, 0x51,
	0x82, 0x26, 0x78, 0x09, 0x73, 0xc3, 0xbf, 0x70, 0xf1, 0x95, 0x23, 0x0f, 0xbf, 0x82, 0x17, 0x29,
	0xcb, 0x68, 0x99, 0x0b, 0xc2, 0x52, 0x46, 0x49, 0x99, 0xc6, 0x2c, 0x33, 0x92, 0x22, 0x1f, 0xbf,
	0x84, 0x4d, 0x4e, 0xde, 0x97, 0x39, 0x53, 0x79, 0xac, 0x93, 0x4f, 0xf7, 0xce, 0xd4, 0x76, 0x0a,
	0x49, 0x13, 0xc1, 0x09, 0xd3, 0x4c, 0xf0, 0x7b, 0x27, 0xc0, 0xaf, 0x61, 0xeb, 0xe8, 0xb8, 0xd0,
	0x65, 0x2a, 0x0c, 0x7f, 0xe0, 0x9b, 0xe1, 0x2d, 0xe0, 0x82, 0xca, 0x9c, 0x29, 0x35, 0x9e, 0x09,
	0xa3, 0x3d, 0x80, 0xd5, 0xad, 0xba, 0xaa, 0xeb, 0xdb, 0xe8, 0xc3, 0xa0, 0x78, 0x05, 0x0b, 0xc3,
	0x0f, 0x86, 0x1a, 0xa7, 0x19, 0x20, 0x1c, 0xb0, 0x67, 0xb1, 0x1d, 0xa6, 0x04, 0xf9, 0xd6, 0x8b,
	0x32, 0x49, 0x42, 0x95, 0x42, 0xd3, 0x68, 0x07, 0x0b, 0x4b, 0xe4, 0x9c, 0xbf, 0x19, 0x68, 0x46,
	0x66, 0x27, 0x78, 0x01, 0x41, 0xc6, 0x94, 0x46, 0x9e, 0x45, 0x89, 0x28, 0x8e, 0xc8, 0x8f, 0x0e,
	0xb0, 0xfa, 0xdc, 0x9c, 0x64, 0x7f, 0x19, 0xf6, 0xc7, 0xc3, 0xe0, 0x1a, 0x96, 0xd6, 0x84, 0xd2,
	0xb1, 0xd4, 0x4e, 0xc2, 0x1a, 0x96, 0x8c, 0x97, 0x85, 0x14, 0x7b, 0x69, 0xd7, 0x3d, 0xa2, 0xe3,
	0xb7, 0x07, 0xcf, 0x64, 0xdd, 0x36, 0xfd, 0xed, 0x7b, 0x3d, 0xb0, 0x5e, 0x06, 0xd6, 0x0d, 0x20,
	0x7d, 0x2c, 0x68, 0x69, 0xb8, 0x2a, 0x68, 0xe2, 0x12, 0xff, 0xff, 0x22, 0xd2, 0x70, 0xce, 0xf8,
	0x1e, 0x79, 0xf8, 0x29, 0x3c, 0x21, 0xb4, 0xc8, 0xc4, 0xd1, 0x96, 0xbe, 0xcd, 0x81, 0xd0, 0x8c,
	0x6a, 0x5b, 0x4d, 0x47, 0x3b, 0x03, 0x7b, 0xf1, 0x1e, 0x33, 0x9a, 0x8d, 0x9d, 0x86, 0x1f, 0xe7,
	0xdf, 0x66, 0xee, 0x57, 0x9c, 0x42, 0x77, 0xec, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x71,
	0x4d, 0x10, 0x31, 0x02, 0x00, 0x00,
}
