// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package control_go_proto

import (
	fmt "fmt"
	pulse_go_proto "github.com/GoogleCloudPlatform/cloud-ingest/proto/pulse_go_proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies bandwidth allocated to a job run.
type JobRunBandwidth struct {
	JobrunRelRsrcName    string   `protobuf:"bytes,1,opt,name=jobrun_rel_rsrc_name,json=jobrunRelRsrcName,proto3" json:"jobrun_rel_rsrc_name,omitempty"`
	Bandwidth            int64    `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRunBandwidth) Reset()         { *m = JobRunBandwidth{} }
func (m *JobRunBandwidth) String() string { return proto.CompactTextString(m) }
func (*JobRunBandwidth) ProtoMessage()    {}
func (*JobRunBandwidth) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *JobRunBandwidth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRunBandwidth.Unmarshal(m, b)
}
func (m *JobRunBandwidth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRunBandwidth.Marshal(b, m, deterministic)
}
func (m *JobRunBandwidth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRunBandwidth.Merge(m, src)
}
func (m *JobRunBandwidth) XXX_Size() int {
	return xxx_messageInfo_JobRunBandwidth.Size(m)
}
func (m *JobRunBandwidth) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRunBandwidth.DiscardUnknown(m)
}

var xxx_messageInfo_JobRunBandwidth proto.InternalMessageInfo

func (m *JobRunBandwidth) GetJobrunRelRsrcName() string {
	if m != nil {
		return m.JobrunRelRsrcName
	}
	return ""
}

func (m *JobRunBandwidth) GetBandwidth() int64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

// This message contains the agent update source for a corresponding agent
type AgentUpdateSource struct {
	AgentIds             []*pulse_go_proto.AgentId `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	UpdateUrl            string                    `protobuf:"bytes,2,opt,name=update_url,json=updateUrl,proto3" json:"update_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AgentUpdateSource) Reset()         { *m = AgentUpdateSource{} }
func (m *AgentUpdateSource) String() string { return proto.CompactTextString(m) }
func (*AgentUpdateSource) ProtoMessage()    {}
func (*AgentUpdateSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *AgentUpdateSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentUpdateSource.Unmarshal(m, b)
}
func (m *AgentUpdateSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentUpdateSource.Marshal(b, m, deterministic)
}
func (m *AgentUpdateSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentUpdateSource.Merge(m, src)
}
func (m *AgentUpdateSource) XXX_Size() int {
	return xxx_messageInfo_AgentUpdateSource.Size(m)
}
func (m *AgentUpdateSource) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentUpdateSource.DiscardUnknown(m)
}

var xxx_messageInfo_AgentUpdateSource proto.InternalMessageInfo

func (m *AgentUpdateSource) GetAgentIds() []*pulse_go_proto.AgentId {
	if m != nil {
		return m.AgentIds
	}
	return nil
}

func (m *AgentUpdateSource) GetUpdateUrl() string {
	if m != nil {
		return m.UpdateUrl
	}
	return ""
}

// A list containing the download source URL of each agent associated with a
// given project
type AgentUpdate struct {
	AgentUpdateSources   []*AgentUpdateSource `protobuf:"bytes,1,rep,name=agent_update_sources,json=agentUpdateSources,proto3" json:"agent_update_sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AgentUpdate) Reset()         { *m = AgentUpdate{} }
func (m *AgentUpdate) String() string { return proto.CompactTextString(m) }
func (*AgentUpdate) ProtoMessage()    {}
func (*AgentUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{2}
}

func (m *AgentUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentUpdate.Unmarshal(m, b)
}
func (m *AgentUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentUpdate.Marshal(b, m, deterministic)
}
func (m *AgentUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentUpdate.Merge(m, src)
}
func (m *AgentUpdate) XXX_Size() int {
	return xxx_messageInfo_AgentUpdate.Size(m)
}
func (m *AgentUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AgentUpdate proto.InternalMessageInfo

func (m *AgentUpdate) GetAgentUpdateSources() []*AgentUpdateSource {
	if m != nil {
		return m.AgentUpdateSources
	}
	return nil
}

// Specifies the control messages to send to the agents for a specific project.
type Control struct {
	// The bandwidth associated for each active job run in the project.
	JobRunsBandwidths []*JobRunBandwidth `protobuf:"bytes,1,rep,name=job_runs_bandwidths,json=jobRunsBandwidths,proto3" json:"job_runs_bandwidths,omitempty"`
	// The agent update URL for each active agent in the project.
	AgentUpdates         *AgentUpdate `protobuf:"bytes,2,opt,name=agent_updates,json=agentUpdates,proto3" json:"agent_updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Control) Reset()         { *m = Control{} }
func (m *Control) String() string { return proto.CompactTextString(m) }
func (*Control) ProtoMessage()    {}
func (*Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{3}
}

func (m *Control) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Control.Unmarshal(m, b)
}
func (m *Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Control.Marshal(b, m, deterministic)
}
func (m *Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Control.Merge(m, src)
}
func (m *Control) XXX_Size() int {
	return xxx_messageInfo_Control.Size(m)
}
func (m *Control) XXX_DiscardUnknown() {
	xxx_messageInfo_Control.DiscardUnknown(m)
}

var xxx_messageInfo_Control proto.InternalMessageInfo

func (m *Control) GetJobRunsBandwidths() []*JobRunBandwidth {
	if m != nil {
		return m.JobRunsBandwidths
	}
	return nil
}

func (m *Control) GetAgentUpdates() *AgentUpdate {
	if m != nil {
		return m.AgentUpdates
	}
	return nil
}

func init() {
	proto.RegisterType((*JobRunBandwidth)(nil), "cloud_ingest_control.JobRunBandwidth")
	proto.RegisterType((*AgentUpdateSource)(nil), "cloud_ingest_control.AgentUpdateSource")
	proto.RegisterType((*AgentUpdate)(nil), "cloud_ingest_control.AgentUpdate")
	proto.RegisterType((*Control)(nil), "cloud_ingest_control.Control")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d) }

var fileDescriptor_0c5120591600887d = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0xc9, 0x5b, 0x78, 0x35, 0x13, 0x8b, 0x74, 0xec, 0xa2, 0xf8, 0x01, 0x35, 0x20, 0x76,
	0x63, 0x02, 0x75, 0xe3, 0xd6, 0x56, 0x14, 0x5d, 0x88, 0x8c, 0x74, 0xa1, 0x9b, 0x71, 0x92, 0x8c,
	0x69, 0xca, 0x64, 0x6e, 0x99, 0x0f, 0xfc, 0x4b, 0xfe, 0x4c, 0xe9, 0x4c, 0x5b, 0x63, 0x2d, 0xb8,
	0x4a, 0x38, 0x37, 0xe7, 0x3c, 0xe7, 0x5e, 0x82, 0xda, 0x39, 0x48, 0xa3, 0x40, 0x24, 0x73, 0x05,
	0x06, 0x70, 0x37, 0x17, 0x60, 0x0b, 0x5a, 0xc9, 0x92, 0x6b, 0x43, 0x97, 0xb3, 0xc3, 0x68, 0x6e,
	0x85, 0xe6, 0xfe, 0x93, 0xf8, 0x0d, 0xed, 0x3f, 0x40, 0x46, 0xac, 0x1c, 0x31, 0x59, 0x7c, 0x54,
	0x85, 0x99, 0xe2, 0x14, 0x75, 0x67, 0x90, 0x29, 0x2b, 0xa9, 0xe2, 0x82, 0x2a, 0xad, 0x72, 0x2a,
	0x59, 0xcd, 0x7b, 0x41, 0x3f, 0x18, 0x84, 0xa4, 0xe3, 0x67, 0x84, 0x0b, 0xa2, 0x55, 0xfe, 0xc8,
	0x6a, 0x8e, 0x8f, 0x51, 0x98, 0xad, 0xdc, 0xbd, 0x7f, 0xfd, 0x60, 0xd0, 0x22, 0xdf, 0x42, 0x2c,
	0x50, 0xe7, 0xba, 0xe4, 0xd2, 0x4c, 0xe6, 0x05, 0x33, 0xfc, 0x19, 0xac, 0xca, 0x39, 0xbe, 0x42,
	0x21, 0x5b, 0x88, 0xb4, 0x2a, 0x74, 0x2f, 0xe8, 0xb7, 0x06, 0xd1, 0xf0, 0x28, 0xf9, 0xd1, 0xd6,
	0x97, 0x74, 0xce, 0xfb, 0x82, 0xec, 0x32, 0xff, 0xa2, 0xf1, 0x09, 0x42, 0xd6, 0x25, 0x51, 0xab,
	0x84, 0xa3, 0x85, 0x24, 0xf4, 0xca, 0x44, 0x89, 0x78, 0x8a, 0xa2, 0x06, 0x0d, 0xbf, 0xa0, 0xae,
	0xe7, 0x2c, 0x3d, 0xda, 0xe1, 0x57, 0xc8, 0xf3, 0x64, 0xdb, 0x81, 0x92, 0x5f, 0x75, 0x09, 0x66,
	0x9b, 0x92, 0x8e, 0x3f, 0x03, 0xb4, 0x33, 0xf6, 0x0e, 0x3c, 0x41, 0x07, 0x33, 0xc8, 0xa8, 0xb2,
	0x52, 0xd3, 0xf5, 0xe6, 0x2b, 0xca, 0xd9, 0x76, 0xca, 0xc6, 0xd9, 0xdd, 0x61, 0x89, 0x95, 0x7a,
	0xad, 0x68, 0x7c, 0x8b, 0xda, 0xcd, 0xf6, 0xda, 0xad, 0x1b, 0x0d, 0x4f, 0xff, 0xac, 0x4d, 0xf6,
	0x1a, 0x85, 0xf5, 0xe8, 0xe6, 0x75, 0x54, 0x56, 0x66, 0x6a, 0xb3, 0x24, 0x87, 0x3a, 0xbd, 0x03,
	0x28, 0x05, 0x1f, 0x2f, 0x22, 0x9e, 0x04, 0x33, 0xef, 0xa0, 0xea, 0xd4, 0x05, 0x5e, 0xf8, 0xc0,
	0xd4, 0xfd, 0x19, 0xe9, 0x32, 0x96, 0x96, 0x40, 0x9d, 0x90, 0xfd, 0x77, 0x8f, 0xcb, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0xdb, 0xbb, 0xe7, 0x65, 0x02, 0x00, 0x00,
}
