// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package control_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies bandwidth allocated to a job run.
type JobRunBandwidth struct {
	JobrunRelRsrcName    string   `protobuf:"bytes,1,opt,name=jobrun_rel_rsrc_name,json=jobrunRelRsrcName,proto3" json:"jobrun_rel_rsrc_name,omitempty"`
	Bandwidth            int64    `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRunBandwidth) Reset()         { *m = JobRunBandwidth{} }
func (m *JobRunBandwidth) String() string { return proto.CompactTextString(m) }
func (*JobRunBandwidth) ProtoMessage()    {}
func (*JobRunBandwidth) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *JobRunBandwidth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRunBandwidth.Unmarshal(m, b)
}
func (m *JobRunBandwidth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRunBandwidth.Marshal(b, m, deterministic)
}
func (m *JobRunBandwidth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRunBandwidth.Merge(m, src)
}
func (m *JobRunBandwidth) XXX_Size() int {
	return xxx_messageInfo_JobRunBandwidth.Size(m)
}
func (m *JobRunBandwidth) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRunBandwidth.DiscardUnknown(m)
}

var xxx_messageInfo_JobRunBandwidth proto.InternalMessageInfo

func (m *JobRunBandwidth) GetJobrunRelRsrcName() string {
	if m != nil {
		return m.JobrunRelRsrcName
	}
	return ""
}

func (m *JobRunBandwidth) GetBandwidth() int64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

// Specifies the control messages to send to the agents for a specific project.
type Control struct {
	// The bandwidth associated for each active job run in the project.
	JobRunsBandwidths    []*JobRunBandwidth `protobuf:"bytes,1,rep,name=job_runs_bandwidths,json=jobRunsBandwidths,proto3" json:"job_runs_bandwidths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Control) Reset()         { *m = Control{} }
func (m *Control) String() string { return proto.CompactTextString(m) }
func (*Control) ProtoMessage()    {}
func (*Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *Control) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Control.Unmarshal(m, b)
}
func (m *Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Control.Marshal(b, m, deterministic)
}
func (m *Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Control.Merge(m, src)
}
func (m *Control) XXX_Size() int {
	return xxx_messageInfo_Control.Size(m)
}
func (m *Control) XXX_DiscardUnknown() {
	xxx_messageInfo_Control.DiscardUnknown(m)
}

var xxx_messageInfo_Control proto.InternalMessageInfo

func (m *Control) GetJobRunsBandwidths() []*JobRunBandwidth {
	if m != nil {
		return m.JobRunsBandwidths
	}
	return nil
}

func init() {
	proto.RegisterType((*JobRunBandwidth)(nil), "cloud_ingest_control.JobRunBandwidth")
	proto.RegisterType((*Control)(nil), "cloud_ingest_control.Control")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d) }

var fileDescriptor_0c5120591600887d = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0xce, 0xc9, 0x2f, 0x4d,
	0x89, 0xcf, 0xcc, 0x4b, 0x4f, 0x2d, 0x2e, 0x89, 0x87, 0xca, 0x29, 0x25, 0x70, 0xf1, 0x7b, 0xe5,
	0x27, 0x05, 0x95, 0xe6, 0x39, 0x25, 0xe6, 0xa5, 0x94, 0x67, 0xa6, 0x94, 0x64, 0x08, 0xe9, 0x73,
	0x89, 0x64, 0xe5, 0x27, 0x15, 0x95, 0xe6, 0xc5, 0x17, 0xa5, 0xe6, 0xc4, 0x17, 0x15, 0x17, 0x25,
	0xc7, 0xe7, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x09, 0x42, 0xe4, 0x82,
	0x52, 0x73, 0x82, 0x8a, 0x8b, 0x92, 0xfd, 0x12, 0x73, 0x53, 0x85, 0x64, 0xb8, 0x38, 0x93, 0x60,
	0xba, 0x25, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x10, 0x02, 0x4a, 0x09, 0x5c, 0xec, 0xce, 0x10,
	0xcb, 0x84, 0x42, 0xb9, 0x84, 0xb3, 0xf2, 0x93, 0xe2, 0x8b, 0x4a, 0xf3, 0x8a, 0xe3, 0xe1, 0x0a,
	0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x54, 0xf5, 0xb0, 0x39, 0x50, 0x0f, 0xcd, 0x75,
	0x60, 0xfb, 0x83, 0x4a, 0xf3, 0x8a, 0xe1, 0x22, 0xc5, 0x4e, 0x42, 0x51, 0x02, 0x50, 0xd5, 0xf1,
	0xe9, 0xf9, 0xf1, 0x60, 0xdf, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x53, 0xf5, 0xfe, 0xfb, 0x05, 0x01, 0x00, 0x00,
}
