// Code generated by MockGen. DO NOT EDIT.
// Source: random.go

package datagenerator

import (
	gomock "github.com/golang/mock/gomock"
)

// MockDistribution is a mock of Distribution interface
type MockDistribution struct {
	ctrl     *gomock.Controller
	recorder *MockDistributionMockRecorder
}

// MockDistributionMockRecorder is the mock recorder for MockDistribution
type MockDistributionMockRecorder struct {
	mock *MockDistribution
}

// NewMockDistribution creates a new mock instance
func NewMockDistribution(ctrl *gomock.Controller) *MockDistribution {
	mock := &MockDistribution{ctrl: ctrl}
	mock.recorder = &MockDistributionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDistribution) EXPECT() *MockDistributionMockRecorder {
	return _m.recorder
}

// GetNext mocks base method
func (_m *MockDistribution) GetNext() int {
	ret := _m.ctrl.Call(_m, "GetNext")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNext indicates an expected call of GetNext
func (_mr *MockDistributionMockRecorder) GetNext() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetNext")
}

// Max mocks base method
func (_m *MockDistribution) Max() int {
	ret := _m.ctrl.Call(_m, "Max")
	ret0, _ := ret[0].(int)
	return ret0
}

// Max indicates an expected call of Max
func (_mr *MockDistributionMockRecorder) Max() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Max")
}
