// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listfile.proto

package listfile_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// List File Header specification.
type ListFileHeader struct {
	// The Job Run Version of the job that produced this list file.
	JobRunVersion        string   `protobuf:"bytes,1,opt,name=job_run_version,json=jobRunVersion,proto3" json:"job_run_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFileHeader) Reset()         { *m = ListFileHeader{} }
func (m *ListFileHeader) String() string { return proto.CompactTextString(m) }
func (*ListFileHeader) ProtoMessage()    {}
func (*ListFileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_944e22c88393983d, []int{0}
}

func (m *ListFileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFileHeader.Unmarshal(m, b)
}
func (m *ListFileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFileHeader.Marshal(b, m, deterministic)
}
func (m *ListFileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFileHeader.Merge(m, src)
}
func (m *ListFileHeader) XXX_Size() int {
	return xxx_messageInfo_ListFileHeader.Size(m)
}
func (m *ListFileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ListFileHeader proto.InternalMessageInfo

func (m *ListFileHeader) GetJobRunVersion() string {
	if m != nil {
		return m.JobRunVersion
	}
	return ""
}

// List File Entry specification.
type ListFileEntry struct {
	// Types that are valid to be assigned to Entry:
	//	*ListFileEntry_FileInfo
	//	*ListFileEntry_DirectoryInfo
	Entry                isListFileEntry_Entry `protobuf_oneof:"entry"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListFileEntry) Reset()         { *m = ListFileEntry{} }
func (m *ListFileEntry) String() string { return proto.CompactTextString(m) }
func (*ListFileEntry) ProtoMessage()    {}
func (*ListFileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_944e22c88393983d, []int{1}
}

func (m *ListFileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFileEntry.Unmarshal(m, b)
}
func (m *ListFileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFileEntry.Marshal(b, m, deterministic)
}
func (m *ListFileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFileEntry.Merge(m, src)
}
func (m *ListFileEntry) XXX_Size() int {
	return xxx_messageInfo_ListFileEntry.Size(m)
}
func (m *ListFileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ListFileEntry proto.InternalMessageInfo

type isListFileEntry_Entry interface {
	isListFileEntry_Entry()
}

type ListFileEntry_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type ListFileEntry_DirectoryInfo struct {
	DirectoryInfo *DirectoryInfo `protobuf:"bytes,2,opt,name=directory_info,json=directoryInfo,proto3,oneof"`
}

func (*ListFileEntry_FileInfo) isListFileEntry_Entry() {}

func (*ListFileEntry_DirectoryInfo) isListFileEntry_Entry() {}

func (m *ListFileEntry) GetEntry() isListFileEntry_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ListFileEntry) GetFileInfo() *FileInfo {
	if x, ok := m.GetEntry().(*ListFileEntry_FileInfo); ok {
		return x.FileInfo
	}
	return nil
}

func (m *ListFileEntry) GetDirectoryInfo() *DirectoryInfo {
	if x, ok := m.GetEntry().(*ListFileEntry_DirectoryInfo); ok {
		return x.DirectoryInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ListFileEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ListFileEntry_OneofMarshaler, _ListFileEntry_OneofUnmarshaler, _ListFileEntry_OneofSizer, []interface{}{
		(*ListFileEntry_FileInfo)(nil),
		(*ListFileEntry_DirectoryInfo)(nil),
	}
}

func _ListFileEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ListFileEntry)
	// entry
	switch x := m.Entry.(type) {
	case *ListFileEntry_FileInfo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileInfo); err != nil {
			return err
		}
	case *ListFileEntry_DirectoryInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DirectoryInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ListFileEntry.Entry has unexpected type %T", x)
	}
	return nil
}

func _ListFileEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ListFileEntry)
	switch tag {
	case 1: // entry.file_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileInfo)
		err := b.DecodeMessage(msg)
		m.Entry = &ListFileEntry_FileInfo{msg}
		return true, err
	case 2: // entry.directory_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DirectoryInfo)
		err := b.DecodeMessage(msg)
		m.Entry = &ListFileEntry_DirectoryInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ListFileEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ListFileEntry)
	// entry
	switch x := m.Entry.(type) {
	case *ListFileEntry_FileInfo:
		s := proto.Size(x.FileInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ListFileEntry_DirectoryInfo:
		s := proto.Size(x.DirectoryInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Represents a single file’s metadata.
type FileInfo struct {
	// Full path of the file in the format used by the local OS.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Last modified time of the file in seconds since the epoch.
	LastModifiedTime int64 `protobuf:"varint,2,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	// The size of the file in bytes.
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_944e22c88393983d, []int{2}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileInfo) GetLastModifiedTime() int64 {
	if m != nil {
		return m.LastModifiedTime
	}
	return 0
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// Represents a single directory's metadata.
type DirectoryInfo struct {
	// The full path of the directory in the format used by the local OS.
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryInfo) Reset()         { *m = DirectoryInfo{} }
func (m *DirectoryInfo) String() string { return proto.CompactTextString(m) }
func (*DirectoryInfo) ProtoMessage()    {}
func (*DirectoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_944e22c88393983d, []int{3}
}

func (m *DirectoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryInfo.Unmarshal(m, b)
}
func (m *DirectoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryInfo.Marshal(b, m, deterministic)
}
func (m *DirectoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryInfo.Merge(m, src)
}
func (m *DirectoryInfo) XXX_Size() int {
	return xxx_messageInfo_DirectoryInfo.Size(m)
}
func (m *DirectoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryInfo proto.InternalMessageInfo

func (m *DirectoryInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*ListFileHeader)(nil), "cloud_ingest_listfile.ListFileHeader")
	proto.RegisterType((*ListFileEntry)(nil), "cloud_ingest_listfile.ListFileEntry")
	proto.RegisterType((*FileInfo)(nil), "cloud_ingest_listfile.FileInfo")
	proto.RegisterType((*DirectoryInfo)(nil), "cloud_ingest_listfile.DirectoryInfo")
}

func init() { proto.RegisterFile("listfile.proto", fileDescriptor_944e22c88393983d) }

var fileDescriptor_944e22c88393983d = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xf5, 0x4f, 0x3b, 0x92, 0xa8, 0x2b, 0x42, 0x6f, 0x4a, 0x14, 0xf1, 0x20, 0x39,
	0xe8, 0xc5, 0x93, 0x87, 0xa2, 0x52, 0xc1, 0x5e, 0x82, 0x78, 0xf0, 0xb2, 0x26, 0xdd, 0x49, 0x9d,
	0x92, 0xec, 0x94, 0xdd, 0x8d, 0x50, 0xbf, 0x90, 0x5f, 0x53, 0xb2, 0x4d, 0x40, 0xa1, 0x9e, 0x76,
	0x98, 0xb7, 0xef, 0xf7, 0xde, 0xb2, 0x10, 0x95, 0x64, 0x5d, 0x41, 0x25, 0x26, 0x0b, 0xc3, 0x8e,
	0xc5, 0xf1, 0xb4, 0xe4, 0x5a, 0x49, 0xd2, 0x33, 0xb4, 0x4e, 0x76, 0x62, 0x7c, 0x0b, 0xd1, 0x33,
	0x59, 0xf7, 0x48, 0x25, 0x8e, 0x31, 0x53, 0x68, 0xc4, 0x05, 0xec, 0xcf, 0x39, 0x97, 0xa6, 0xd6,
	0xf2, 0x13, 0x8d, 0x25, 0xd6, 0xc3, 0xe0, 0x34, 0xb8, 0x1c, 0xa4, 0xe1, 0x9c, 0xf3, 0xb4, 0xd6,
	0xaf, 0xab, 0x65, 0xfc, 0x1d, 0x40, 0xd8, 0x59, 0x1f, 0xb4, 0x33, 0x4b, 0x71, 0x07, 0x83, 0x86,
	0x29, 0x49, 0x17, 0xec, 0x3d, 0x7b, 0xd7, 0x27, 0xc9, 0xda, 0xd8, 0xa4, 0x31, 0x3d, 0xe9, 0x82,
	0xc7, 0x1b, 0x69, 0xbf, 0x68, 0x67, 0x31, 0x81, 0x48, 0x91, 0xc1, 0xa9, 0x63, 0xb3, 0x5c, 0x41,
	0x36, 0x3d, 0xe4, 0xfc, 0x1f, 0xc8, 0x7d, 0x77, 0xb9, 0x25, 0x85, 0xea, 0xf7, 0x62, 0xb4, 0x0b,
	0xdb, 0xd8, 0xf4, 0x8a, 0xdf, 0xa1, 0xdf, 0xe5, 0x09, 0x01, 0x5b, 0x8b, 0xcc, 0x7d, 0xb4, 0x4f,
	0xf2, 0xb3, 0xb8, 0x02, 0x51, 0x66, 0xd6, 0xc9, 0x8a, 0x15, 0x15, 0x84, 0x4a, 0x3a, 0xaa, 0xd0,
	0x67, 0xf7, 0xd2, 0x83, 0x46, 0x99, 0xb4, 0xc2, 0x0b, 0x55, 0xd8, 0x10, 0x2c, 0x7d, 0xe1, 0xb0,
	0xe7, 0x75, 0x3f, 0xc7, 0x67, 0x10, 0xfe, 0x29, 0xb3, 0x2e, 0x66, 0x74, 0xf4, 0x76, 0xd8, 0x55,
	0x97, 0x33, 0x96, 0xfe, 0x5b, 0xf2, 0x1d, 0x7f, 0xdc, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x36, 0x3d, 0x38, 0xaf, 0x01, 0x00, 0x00,
}
